import React from 'react';

const About = () => {
    return (
        <div className='m-10 p-4 '>
            <h1 className='sm:text-4xl text-2xl font-bold mt-6 text-gray-900 mb-6'>About this blog app</h1>
            <p className='mx-auto leading-relaxed text-base mb-4'>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consectetur tenetur nihil id necessitatibus mollitia quo hic nisi dolorem nemo veritatis, vero maiores nostrum doloremque error alias expedita vel dolorum adipisci quis? Vero ex magnam praesentium, porro aliquid corrupti in, necessitatibus fugiat, inventore eius veniam perspiciatis dolorum dicta. Repudiandae, enim quaerat.    </p>
            <p className='mx-auto leading-relaxed text-base mb-4'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aut dolorum facilis ipsa iste deserunt eius? Cupiditate et perspiciatis, eligendi rem quis vero molestiae eos error aspernatur nesciunt itaque, ut delectus magnam nam minus ipsum. Aliquam aut molestiae, possimus enim necessitatibus ea architecto accusantium ad fugiat delectus temporibus, corporis quo magni dolorem mollitia iste reprehenderit sapiente praesentium iure. Iusto optio, quod iste vitae, velit quae perferendis rerum eius omnis ipsum ad aperiam cupiditate dolore nemo dicta a quaerat voluptate quas provident qui! Non possimus doloremque aliquam distinctio repellat molestias vitae quia, ipsam pariatur, repellendus suscipit corporis delectus illum cumque eveniet quisquam.</p>
            <p className='mx-auto leading-relaxed text-base mb-4'>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Cupiditate, eveniet doloribus corporis aperiam sapiente voluptates? Atque aperiam recusandae, nihil unde inventore labore, architecto vitae minima est mollitia magnam deserunt fuga rem at eos modi amet, officia tempore expedita eveniet assumenda optio laboriosam veniam. Possimus ipsa laborum sint cupiditate sequi expedita quia? Ipsa recusandae amet iure consequuntur, vero inventore magni? Ea dolor magni fuga placeat ratione, suscipit veritatis rerum eveniet distinctio! Animi corporis at quaerat dolore impedit quos minus voluptate assumenda, doloremque tempore molestias voluptates ab sit aliquid maxime dignissimos cum numquam tenetur, alias quidem distinctio fugit sequi et! Cupiditate animi laboriosam nihil! Dolorum voluptas eveniet, at recusandae sed sit beatae accusamus quidem, enim maxime reiciendis blanditiis ut ex labore eaque distinctio quis reprehenderit incidunt sint repellendus optio animi explicabo earum deserunt! Alias, nobis repudiandae nesciunt quo nulla asperiores adipisci? Repudiandae optio molestias perferendis aspernatur veritatis temporibus totam a officia rem magni odio accusantium aliquam, sed explicabo quis qui. Ipsam excepturi, mollitia nemo sint nam corporis, reiciendis esse iste voluptates deleniti natus fugiat saepe corrupti magnam accusantium repellendus in sapiente. Aliquam nemo architecto ratione? Dolor ullam sapiente accusamus perferendis tenetur, suscipit tempore mollitia quidem minus laborum aut quasi! Veniam, dolores doloribus.</p>
        </div>
    );
};

export default About;